#!/bin/bash
# Manual setup script - run these commands one by one if the automated script fails

echo "🔧 Manual iOS Setup Instructions"
echo ""
echo "Run these commands in Terminal (one at a time):"
echo ""
echo "1. Install ffi (required dependency):"
echo "   sudo gem install ffi -v 1.17.3"
echo ""
echo "2. Install CocoaPods (compatible with Ruby 2.6):"
echo "   sudo gem install cocoapods -v 1.11.3"
echo ""
echo "3. Verify installation:"
echo "   pod --version"
echo ""
echo "4. Install pods:"
echo "   cd ios/App"
echo "   pod install"
echo "   cd ../.."
echo ""
echo "5. Sync Capacitor:"
echo "   npx cap sync ios"
echo ""
echo "6. Open Xcode:"
echo "   open ios/App/App.xcworkspace"
echo ""
