const { execSync } = require('node:child_process');
const fs = require('node:fs');
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
function sh(c){ return execSync(c,{stdio:['ignore','pipe','ignore']}).toString().trim(); }
const sha = (process.env.BUILD_SHA || sh('git rev-parse --short HEAD'));
const time = new Date().toISOString();
const content = `// auto-generated by scripts/gen-version.js
export const APP_VERSION = "${pkg.version}";
export const BUILD_SHA   = "${sha}";
export const BUILD_TIME  = "${time}";
`;
// Write to the correct path based on where the script is called from
const versionPath = process.cwd().includes('/client') ? 'src/version.ts' : 'client/src/version.ts';
fs.writeFileSync(versionPath, content);
console.log('Wrote client/src/version.ts', { version: pkg.version, sha, time });
