#!/bin/bash

# Fan Club Z - Automated Environment Setup Script
# Creates all 3 env files (contracts/.env, server/.env, client/.env.local) with user prompts

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 Fan Club Z - Environment Setup${NC}"
echo "================================"
echo ""

# Get project root (parent of env-files directory)
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

echo -e "${GREEN}📁 Project root: $PROJECT_ROOT${NC}"
echo ""

# Check if files already exist
WARN_EXISTING=false
if [ -f "contracts/.env" ]; then
    echo -e "${YELLOW}⚠️  contracts/.env already exists${NC}"
    WARN_EXISTING=true
fi
if [ -f "server/.env" ]; then
    echo -e "${YELLOW}⚠️  server/.env already exists${NC}"
    WARN_EXISTING=true
fi
if [ -f "client/.env.local" ]; then
    echo -e "${YELLOW}⚠️  client/.env.local already exists${NC}"
    WARN_EXISTING=true
fi

if [ "$WARN_EXISTING" = true ]; then
    echo ""
    read -p "Some env files already exist. Continue? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${RED}❌ Cancelled${NC}"
        exit 1
    fi
    echo ""
fi

# Prompt for required values
echo -e "${BLUE}📝 Please provide the following information:${NC}"
echo ""

# Private Key
echo -e "${YELLOW}1. Deployer Private Key (from MetaMask/your wallet):${NC}"
echo "   (This will be used for contract deployment)"
read -sp "   Private Key: " DEPLOYER_PRIVATE_KEY
echo ""
if [ -z "$DEPLOYER_PRIVATE_KEY" ]; then
    echo -e "${RED}❌ Error: Private key is required${NC}"
    exit 1
fi

# WalletConnect Project ID
echo ""
echo -e "${YELLOW}2. WalletConnect Project ID:${NC}"
echo "   (Get from: https://cloud.walletconnect.com/)"
read -p "   Project ID: " WC_PROJECT_ID
if [ -z "$WC_PROJECT_ID" ]; then
    echo -e "${YELLOW}⚠️  Warning: WalletConnect Project ID not provided${NC}"
    echo "   You can add this later to client/.env.local"
fi

# Optional: Alchemy API Key
echo ""
echo -e "${YELLOW}3. Alchemy API Key (optional, for better RPC):${NC}"
read -p "   Alchemy API Key (press Enter to skip): " ALCHEMY_API_KEY

# Optional: Basescan API Key
echo ""
echo -e "${YELLOW}4. Basescan API Key (optional, for contract verification):${NC}"
read -p "   Basescan API Key (press Enter to skip): " BASESCAN_API_KEY

echo ""
echo -e "${GREEN}✅ Creating environment files...${NC}"
echo ""

# ========== CONTRACTS/.ENV ==========
echo "📝 Creating contracts/.env..."

mkdir -p contracts

cat > contracts/.env << EOF
# Fan Club Z Escrow - Deployment Configuration
# Generated by setup-env.sh on $(date)

# ========== Wallet & Keys ==========
DEPLOYER_PRIVATE_KEY=$DEPLOYER_PRIVATE_KEY

# ========== RPC Endpoints ==========
BASE_SEPOLIA_RPC_URL=https://sepolia.base.org
ALCHEMY_API_KEY=${ALCHEMY_API_KEY:-}
EOF

if [ -n "$ALCHEMY_API_KEY" ]; then
    echo "ALCHEMY_BASE_SEPOLIA_RPC_URL=https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}" >> contracts/.env
fi

cat >> contracts/.env << EOF

# ========== Contract Addresses ==========
# USDC Token address on Base Sepolia
USDC_ADDRESS=0x036CbD53842c5426634e7929541eC2318f3dCF7e

# ========== Escrow Configuration ==========
# Platform fee in basis points (250 = 2.5%)
PLATFORM_FEE_BPS=250

# ========== Verification ==========
BASESCAN_API_KEY=${BASESCAN_API_KEY:-}

# ========== Environment ==========
DEPLOY_ENV=qa
EOF

echo -e "   ${GREEN}✅ contracts/.env created${NC}"

# ========== SERVER/.ENV ==========
echo "📝 Creating server/.env..."

mkdir -p server

# Check if server/.env already has content we should preserve
if [ -f "server/.env" ]; then
    # Backup existing
    cp server/.env server/.env.backup.$(date +%s)
    echo -e "   ${YELLOW}⚠️  Backed up existing server/.env${NC}"
fi

# Read existing server/.env if it exists and extract important vars
if [ -f "server/.env" ]; then
    EXISTING_DB_URL=$(grep "^DATABASE_URL=" server/.env | cut -d '=' -f2- || true)
    EXISTING_SUPABASE_URL=$(grep "^SUPABASE_URL=" server/.env | cut -d '=' -f2- || true)
    EXISTING_SUPABASE_KEY=$(grep "^SUPABASE_SERVICE_ROLE_KEY=" server/.env | cut -d '=' -f2- || true)
fi

cat > server/.env << EOF
# Fan Club Z Server - Environment Configuration
# Generated by setup-env.sh on $(date)

# ========== Database ==========
DATABASE_URL=${EXISTING_DB_URL:-your_database_url_here}
SUPABASE_URL=${EXISTING_SUPABASE_URL:-your_supabase_url_here}
SUPABASE_SERVICE_ROLE_KEY=${EXISTING_SUPABASE_KEY:-your_supabase_key_here}

# ========== Base Sepolia Escrow ==========
# This will be filled after contract deployment
BASE_ESCROW_ADDRESS=

# ========== Payment Configuration ==========
VITE_FCZ_BASE_ENABLE=1
VITE_FCZ_BASE_CHAIN_ID=84532
VITE_FCZ_BASE_READONLY=0
VITE_FCZ_BASE_DEPOSITS=1
VITE_FCZ_BASE_WITHDRAWALS=1
VITE_FCZ_BASE_BETS=1

# ========== Environment ==========
NODE_ENV=development
PORT=3001
EOF

echo -e "   ${GREEN}✅ server/.env created${NC}"
echo -e "   ${YELLOW}⚠️  Note: BASE_ESCROW_ADDRESS will be empty until you deploy the contract${NC}"

# ========== CLIENT/.ENV.LOCAL ==========
echo "📝 Creating client/.env.local..."

mkdir -p client

cat > client/.env.local << EOF
# Fan Club Z Client - Environment Configuration
# Generated by setup-env.sh on $(date)

# ========== WalletConnect ==========
VITE_WC_PROJECT_ID=${WC_PROJECT_ID:-}

# ========== Base Sepolia Configuration ==========
VITE_FCZ_BASE_ENABLE=1
VITE_FCZ_BASE_CHAIN_ID=84532
VITE_FCZ_BASE_READONLY=0
VITE_FCZ_BASE_DEPOSITS=1
VITE_FCZ_BASE_WITHDRAWALS=1
VITE_FCZ_BASE_BETS=1

# ========== USDC Token Address ==========
VITE_USDC_ADDRESS_BASE_SEPOLIA=0x036CbD53842c5426634e7929541eC2318f3dCF7e
VITE_USDC_DECIMALS=6

# ========== Escrow Contract ==========
# This will be filled after contract deployment
VITE_BASE_ESCROW_ADDRESS=

# ========== RPC Endpoints ==========
VITE_BASE_SEPOLIA_RPC_URL=https://sepolia.base.org
EOF

if [ -n "$ALCHEMY_API_KEY" ]; then
    echo "VITE_ALCHEMY_BASE_SEPOLIA_RPC_URL=https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}" >> client/.env.local
fi

cat >> client/.env.local << EOF

# ========== Debug (optional) ==========
# VITE_DEBUG_LOGS=true
EOF

echo -e "   ${GREEN}✅ client/.env.local created${NC}"
echo ""

# Summary
echo "================================"
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo ""
echo "📋 Created Files:"
echo "   ✅ contracts/.env"
echo "   ✅ server/.env"
echo "   ✅ client/.env.local"
echo ""
echo "📝 Next Steps:"
echo "   1. Deploy escrow contract:"
echo "      cd contracts && forge script script/DeployEscrow.s.sol:DeployEscrow \\"
echo "        --rpc-url \$BASE_SEPOLIA_RPC_URL \\"
echo "        --private-key \$DEPLOYER_PRIVATE_KEY \\"
echo "        --broadcast"
echo ""
echo "   2. Copy the deployed contract address to:"
echo "      - server/.env: BASE_ESCROW_ADDRESS=0x..."
echo "      - client/.env.local: VITE_BASE_ESCROW_ADDRESS=0x..."
echo ""
echo "   3. Restart servers:"
echo "      cd server && npm run dev"
echo "      cd client && npm run dev"
echo ""
echo -e "${GREEN}🎉 Ready to deploy!${NC}"

